### ISSUE TITLE
java.lang.ClassNotFoundException: com.iot.video.app.kafka.collector.VideoStreamCollector

### ISSUE THREAD

**Issue by kleysonr** [baghelamit/video-stream-analytics#1]
Hi,

Trying to compile the StreamCollector and getting the the following error:

```
$ mvn clean package exec:java -Dexec.mainClass="com.iot.video.app.kafka.collector.VideoStreamCollector" -Dexec.cleanupDaemonThreads=false
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] video-stream-processor
[INFO] video-stream-collector
[INFO] Video Stream Analytics
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building video-stream-processor 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ video-stream-processor ---
[INFO] Deleting /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/target
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install-file (install-external) @ video-stream-processor ---
[INFO] pom.xml not found in opencv-320.jar
[INFO] Installing /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/lib/opencv/opencv-320.jar to /home/kleysonr/.m2/repository/opencv/opencv/3.2.0/opencv-3.2.0.jar
[INFO] Installing /tmp/mvninstall3705405067332435574.pom to /home/kleysonr/.m2/repository/opencv/opencv/3.2.0/opencv-3.2.0.pom
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ video-stream-processor ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ video-stream-processor ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 4 source files to /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ video-stream-processor ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ video-stream-processor ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ video-stream-processor ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ video-stream-processor ---
[INFO] Building jar: /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/target/video-stream-processor-1.0.0.jar
[INFO] 
[INFO] --- maven-shade-plugin:3.0.0:shade (default) @ video-stream-processor ---
[INFO] Including org.apache.spark:spark-core_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.avro:avro:jar:1.7.7 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-core-asl:jar:1.9.13 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 in the shaded jar.
[INFO] Including com.thoughtworks.paranamer:paranamer:jar:2.3 in the shaded jar.
[INFO] Including org.apache.commons:commons-compress:jar:1.4.1 in the shaded jar.
[INFO] Including org.tukaani:xz:jar:1.0 in the shaded jar.
[INFO] Including org.apache.avro:avro-mapred:jar:hadoop2:1.7.7 in the shaded jar.
[INFO] Including org.apache.avro:avro-ipc:jar:1.7.7 in the shaded jar.
[INFO] Including org.apache.avro:avro-ipc:jar:tests:1.7.7 in the shaded jar.
[INFO] Including com.twitter:chill_2.11:jar:0.8.0 in the shaded jar.
[INFO] Including com.esotericsoftware:kryo-shaded:jar:3.0.3 in the shaded jar.
[INFO] Including com.esotericsoftware:minlog:jar:1.3.0 in the shaded jar.
[INFO] Including org.objenesis:objenesis:jar:2.1 in the shaded jar.
[INFO] Including com.twitter:chill-java:jar:0.8.0 in the shaded jar.
[INFO] Including org.apache.xbean:xbean-asm5-shaded:jar:4.4 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-client:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-common:jar:2.6.5 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.2 in the shaded jar.
[INFO] Including xmlenc:xmlenc:jar:0.52 in the shaded jar.
[INFO] Including commons-httpclient:commons-httpclient:jar:3.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including commons-collections:commons-collections:jar:3.2.2 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including commons-configuration:commons-configuration:jar:1.6 in the shaded jar.
[INFO] Including commons-digester:commons-digester:jar:1.8 in the shaded jar.
[INFO] Including commons-beanutils:commons-beanutils:jar:1.7.0 in the shaded jar.
[INFO] Including commons-beanutils:commons-beanutils-core:jar:1.8.0 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:2.5.0 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.2.4 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-auth:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15 in the shaded jar.
[INFO] Including org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15 in the shaded jar.
[INFO] Including org.apache.directory.api:api-asn1-api:jar:1.0.0-M20 in the shaded jar.
[INFO] Including org.apache.directory.api:api-util:jar:1.0.0-M20 in the shaded jar.
[INFO] Including org.apache.curator:curator-client:jar:2.6.0 in the shaded jar.
[INFO] Including org.htrace:htrace-core:jar:3.0.4 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-hdfs:jar:2.6.5 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty-util:jar:6.1.26 in the shaded jar.
[INFO] Including xerces:xercesImpl:jar:2.9.1 in the shaded jar.
[INFO] Including xml-apis:xml-apis:jar:1.3.04 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-client:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-server-common:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-api:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-yarn-common:jar:2.6.5 in the shaded jar.
[INFO] Including javax.xml.bind:jaxb-api:jar:2.2.2 in the shaded jar.
[INFO] Including javax.xml.stream:stax-api:jar:1.0-2 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-jaxrs:jar:1.9.13 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-xc:jar:1.9.13 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-annotations:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.spark:spark-launcher_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.spark:spark-network-common_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.fusesource.leveldbjni:leveldbjni-all:jar:1.8 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.spark:spark-network-shuffle_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.spark:spark-unsafe_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including net.java.dev.jets3t:jets3t:jar:0.9.3 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.3.3 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.3.6 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.8 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1.1 in the shaded jar.
[INFO] Including mx4j:mx4j:jar:3.0.2 in the shaded jar.
[INFO] Including javax.mail:mail:jar:1.4.7 in the shaded jar.
[INFO] Including org.bouncycastle:bcprov-jdk15on:jar:1.51 in the shaded jar.
[INFO] Including com.jamesmurty.utils:java-xmlbuilder:jar:1.0 in the shaded jar.
[INFO] Including net.iharder:base64:jar:2.3.8 in the shaded jar.
[INFO] Including org.apache.curator:curator-recipes:jar:2.6.0 in the shaded jar.
[INFO] Including org.apache.curator:curator-framework:jar:2.6.0 in the shaded jar.
[INFO] Including org.apache.zookeeper:zookeeper:jar:3.4.6 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:16.0.1 in the shaded jar.
[INFO] Including javax.servlet:javax.servlet-api:jar:3.1.0 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.5 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.4.1 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:1.3.9 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.16 in the shaded jar.
[INFO] Including org.slf4j:jul-to-slf4j:jar:1.7.16 in the shaded jar.
[INFO] Including org.slf4j:jcl-over-slf4j:jar:1.7.16 in the shaded jar.
[INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.16 in the shaded jar.
[INFO] Including com.ning:compress-lzf:jar:1.0.3 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.2.6 in the shaded jar.
[INFO] Including net.jpountz.lz4:lz4:jar:1.3.0 in the shaded jar.
[INFO] Including org.roaringbitmap:RoaringBitmap:jar:0.5.11 in the shaded jar.
[INFO] Including commons-net:commons-net:jar:2.2 in the shaded jar.
[INFO] Including org.scala-lang:scala-library:jar:2.11.8 in the shaded jar.
[INFO] Including org.json4s:json4s-jackson_2.11:jar:3.2.11 in the shaded jar.
[INFO] Including org.json4s:json4s-core_2.11:jar:3.2.11 in the shaded jar.
[INFO] Including org.json4s:json4s-ast_2.11:jar:3.2.11 in the shaded jar.
[INFO] Including org.scala-lang:scalap:jar:2.11.0 in the shaded jar.
[INFO] Including org.scala-lang:scala-compiler:jar:2.11.0 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-xml_2.11:jar:1.0.1 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-client:jar:2.22.2 in the shaded jar.
[INFO] Including javax.ws.rs:javax.ws.rs-api:jar:2.0.1 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-api:jar:2.4.0-b34 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-utils:jar:2.4.0-b34 in the shaded jar.
[INFO] Including org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34 in the shaded jar.
[INFO] Including org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-locator:jar:2.4.0-b34 in the shaded jar.
[INFO] Including org.javassist:javassist:jar:3.18.1-GA in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-common:jar:2.22.2 in the shaded jar.
[INFO] Including javax.annotation:javax.annotation-api:jar:1.2 in the shaded jar.
[INFO] Including org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.2 in the shaded jar.
[INFO] Including org.glassfish.hk2:osgi-resource-locator:jar:1.0.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-server:jar:2.22.2 in the shaded jar.
[INFO] Including org.glassfish.jersey.media:jersey-media-jaxb:jar:2.22.2 in the shaded jar.
[INFO] Including javax.validation:validation-api:jar:1.1.0.Final in the shaded jar.
[INFO] Including org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.2 in the shaded jar.
[INFO] Including org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.22.2 in the shaded jar.
[INFO] Including io.netty:netty-all:jar:4.0.43.Final in the shaded jar.
[INFO] Including io.netty:netty:jar:3.9.9.Final in the shaded jar.
[INFO] Including com.clearspring.analytics:stream:jar:2.7.0 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-core:jar:3.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-jvm:jar:3.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-json:jar:3.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-graphite:jar:3.1.2 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.6.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.6.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-scala_2.11:jar:2.6.5 in the shaded jar.
[INFO] Including org.scala-lang:scala-reflect:jar:2.11.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.ivy:ivy:jar:2.4.0 in the shaded jar.
[INFO] Including oro:oro:jar:2.0.8 in the shaded jar.
[INFO] Including net.razorvine:pyrolite:jar:4.13 in the shaded jar.
[INFO] Including net.sf.py4j:py4j:jar:0.10.4 in the shaded jar.
[INFO] Including org.apache.spark:spark-tags_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.commons:commons-crypto:jar:1.0.0 in the shaded jar.
[INFO] Including org.spark-project.spark:unused:jar:1.0.0 in the shaded jar.
[INFO] Including org.apache.spark:spark-streaming_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.spark:spark-sql_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including com.univocity:univocity-parsers:jar:2.2.1 in the shaded jar.
[INFO] Including org.apache.spark:spark-sketch_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.spark:spark-catalyst_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.codehaus.janino:janino:jar:3.0.0 in the shaded jar.
[INFO] Including org.codehaus.janino:commons-compiler:jar:3.0.0 in the shaded jar.
[INFO] Including org.antlr:antlr4-runtime:jar:4.5.3 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-column:jar:1.8.2 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-common:jar:1.8.2 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-encoding:jar:1.8.2 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-hadoop:jar:1.8.2 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-format:jar:2.3.1 in the shaded jar.
[INFO] Including org.apache.parquet:parquet-jackson:jar:1.8.2 in the shaded jar.
[INFO] Including org.apache.spark:spark-sql-kafka-0-10_2.11:jar:2.2.0 in the shaded jar.
[INFO] Including org.apache.kafka:kafka-clients:jar:0.10.0.1 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including opencv:opencv:jar:3.2.0 in the shaded jar.
[WARNING] hadoop-yarn-common-2.6.5.jar, hadoop-yarn-client-2.6.5.jar define 2 overlapping classes: 
[WARNING]   - org.apache.hadoop.yarn.client.api.package-info
[WARNING]   - org.apache.hadoop.yarn.client.api.impl.package-info
[WARNING] hadoop-yarn-common-2.6.5.jar, hadoop-yarn-api-2.6.5.jar define 3 overlapping classes: 
[WARNING]   - org.apache.hadoop.yarn.util.package-info
[WARNING]   - org.apache.hadoop.yarn.factories.package-info
[WARNING]   - org.apache.hadoop.yarn.factory.providers.package-info
[WARNING] commons-beanutils-1.7.0.jar, commons-beanutils-core-1.8.0.jar define 82 overlapping classes: 
[WARNING]   - org.apache.commons.beanutils.ConvertUtilsBean
[WARNING]   - org.apache.commons.beanutils.converters.SqlTimeConverter
[WARNING]   - org.apache.commons.beanutils.Converter
[WARNING]   - org.apache.commons.beanutils.converters.FloatArrayConverter
[WARNING]   - org.apache.commons.beanutils.NestedNullException
[WARNING]   - org.apache.commons.beanutils.ConvertingWrapDynaBean
[WARNING]   - org.apache.commons.beanutils.converters.LongArrayConverter
[WARNING]   - org.apache.commons.beanutils.converters.SqlDateConverter
[WARNING]   - org.apache.commons.beanutils.converters.BooleanArrayConverter
[WARNING]   - org.apache.commons.beanutils.converters.StringConverter
[WARNING]   - 72 more...
[WARNING] spark-launcher_2.11-2.2.0.jar, spark-sql_2.11-2.2.0.jar, spark-network-shuffle_2.11-2.2.0.jar, spark-unsafe_2.11-2.2.0.jar, spark-sketch_2.11-2.2.0.jar, spark-sql-kafka-0-10_2.11-2.2.0.jar, spark-streaming_2.11-2.2.0.jar, spark-core_2.11-2.2.0.jar, spark-network-common_2.11-2.2.0.jar, spark-catalyst_2.11-2.2.0.jar, spark-tags_2.11-2.2.0.jar, unused-1.0.0.jar define 1 overlapping classes: 
[WARNING]   - org.apache.spark.unused.UnusedStubClass
[WARNING] commons-beanutils-1.7.0.jar, commons-beanutils-core-1.8.0.jar, commons-collections-3.2.2.jar define 10 overlapping classes: 
[WARNING]   - org.apache.commons.collections.FastHashMap$EntrySet
[WARNING]   - org.apache.commons.collections.FastHashMap$KeySet
[WARNING]   - org.apache.commons.collections.ArrayStack
[WARNING]   - org.apache.commons.collections.FastHashMap$CollectionView$CollectionViewIterator
[WARNING]   - org.apache.commons.collections.FastHashMap$Values
[WARNING]   - org.apache.commons.collections.FastHashMap$CollectionView
[WARNING]   - org.apache.commons.collections.FastHashMap$1
[WARNING]   - org.apache.commons.collections.Buffer
[WARNING]   - org.apache.commons.collections.FastHashMap
[WARNING]   - org.apache.commons.collections.BufferUnderflowException
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/target/video-stream-processor-1.0.0.jar with /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/target/video-stream-processor-1.0.0-shaded.jar
[INFO] Dependency-reduced POM written at: /home/kleysonr/git/x/video-stream-analytics/video-stream-processor/dependency-reduced-pom.xml
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ video-stream-processor ---
[WARNING] 
java.lang.ClassNotFoundException: com.iot.video.app.kafka.collector.VideoStreamCollector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] video-stream-processor ............................. FAILURE [ 15.659 s]
[INFO] video-stream-collector ............................. SKIPPED
[INFO] Video Stream Analytics ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.012 s
[INFO] Finished at: 2017-12-23T18:40:05-02:00
[INFO] Final Memory: 61M/693M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project video-stream-processor: An exception occured while executing the Java class. com.iot.video.app.kafka.collector.VideoStreamCollector -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by baghelamit** [comment]
Please follow the steps given in the article or README files and execute the commands in given order.  Go to "VideoStreamProcessor" folder and then run following commands.

1. mvn clean
2. mvn clean package exec:java -Dexec.mainClass="com.iot.video.app.spark.processor.VideoStreamProcessor"

Once VideoStreamProcessor has started, go to "VideoStreamCollector" folder and issue below command.

mvn clean package exec:java -Dexec.mainClass="com.iot.video.app.kafka.collector.VideoStreamCollector" -Dexec.cleanupDaemonThreads=false

**Comment by kleysonr** [comment]
Ok. I have tried the steps before but didn't work, probably because I've done some changes on the codes. But doing a new git clone and running I didn't get this error anymore.

But I'm facing another issue. I will another issue for it.

Best Regards.
